// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3t1B8BgvDVmEFi8QjYijura50AVA7sZI',
    appId: '1:99796413399:web:0e8ba38131d6699327f992',
    messagingSenderId: '99796413399',
    projectId: 'my-app-2284a',
    authDomain: 'my-app-2284a.firebaseapp.com',
    storageBucket: 'my-app-2284a.appspot.com',
    measurementId: 'G-63QJBTRSJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp37eziLwC3eGVosd1WAGzUmufFG-I4DI',
    appId: '1:99796413399:android:f6c39f96b1ce7ca527f992',
    messagingSenderId: '99796413399',
    projectId: 'my-app-2284a',
    storageBucket: 'my-app-2284a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVU08cNrUz4ZJRHGOtczH9YdiqxQBq3wU',
    appId: '1:99796413399:ios:e34e03a622e62bee27f992',
    messagingSenderId: '99796413399',
    projectId: 'my-app-2284a',
    storageBucket: 'my-app-2284a.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVU08cNrUz4ZJRHGOtczH9YdiqxQBq3wU',
    appId: '1:99796413399:ios:ddfe3c4b3e8d74b227f992',
    messagingSenderId: '99796413399',
    projectId: 'my-app-2284a',
    storageBucket: 'my-app-2284a.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
